### ISSUE TITLE
Cannot load unpacked extension

### ISSUE THREAD

**Issue by spencersolberg** [pomdtr/wsh#9]
Trying to follow the installation and getting stuck at the loading unpacked extension step. Using Arc.

Getting this error:

![image](https://github.com/pomdtr/wsh/assets/46253322/1cd4fbf5-6eec-444b-a703-36031d85c175)

```
Could not load icon 'icons/16.png' specified in 'icons'.
Could not load manifest.
```

Running `convert 48.png -resize 16x16 16.png` inside extension/dist/icons seemed to fix it.

**Comment by pomdtr** [comment]
Sry about that, just fixed it. My .gitignore config was ignoring the icons public folder on my device

**Comment by spencersolberg** [comment]
Yes! Found your post on r/ArcBrowser. I also stumbled upon your Sunbeam project the other day while looking for Deno modules 😂 

Can I ask how you open a shell in a tab instead of the pop up?
